### ISSUE TITLE
Missing API redisClusterAsyncCommandArgvToNode

### ISSUE THREAD

**Issue by SGupta911** [Nordix/hiredis-cluster#104]
Hi Team,

Is there any api similar to "redisClusterAsyncCommandArgv" (uses argc and argv), but that should be for a Node(uses ToNode).

Thanks!

**Comment by bjosv** [comment]
It's not existing today, but a patch is welcomed.

As a stopgap one could call hiredis `redisFormatCommandArgv()` to get the argc+argv-command in the Redis protocol, and then call hiredis-cluster's `redisClusterAsyncFormattedCommandToNode()` with the previous result.
But I guess it would be nice to have that in the API.

**Comment by SGupta911** [comment]
Thank you.
We will try this out.
