### ISSUE TITLE
redisClusterAsyncRetryCallback crash after command timeout

### ISSUE THREAD

**Issue by SS-TruMinds** [Nordix/hiredis-cluster#111]
Hello,

We are using hiredis-cluster Release 0.8.1, and this issue is with regards to a crash we see in our performance testing.

We use async hiredis APIs, and invoke them both from the application and also from hiredis callbacks.
Our application is multi-threaded, and hiredis context object & hiredis API calls are mutex protected.
Our adapter is designed as per the reference hiredis adapter, and we don't do anything special besides calling into hiredis library.
 
We see the following crash a few hours into our test following an adapter timeout:

Crash reason:  SIGSEGV /SEGV_MAPERR
Crash address: 0x1c
Process uptime: not available

Thread 0 (crashed)
`0  libhiredis_cluster.so.0.8!redisClusterAsyncRetryCallback + 0x263`
`1  libhiredis.so.1.0.0!__redisAsyncFree + 0x69`
`2  libhiredis.so.1.0.0!redisProcessCallbacks + 0x1a0`
`3  redisLibmyeventHandler(int, unsigned int, base::SystemInfo) [hiredis_libmyevent.h : 89 + 0x5]`

Please help debug the issue. Let me know if you need any further information.

Thank you.

**Comment by kunalekawde** [comment]
@bjosv could please take a look at this and share some inputs / comments?

**Comment by bjosv** [comment]
hiredis_cluster does not officially support multi-threads since hiredis doesn't support it, but it might work.
Is the cluster contexts also mutex protected together with hiredis?

I can't see any obvious issue when looking around at `redisClusterAsyncRetryCallback + 0x263`, but your output is most likely different than mine.

Could you find out what line of code that is triggering the crash?
You should be able to check this using the start address of `redisClusterAsyncRetryCallback` presented by `objdump` and add 0x263 to it.
Use something like:
`objdump -S -d libhiredis_cluster.so.0.8`

The `-S` i.e. source annotation of the object dump requires the build flag `-g` which hopefully is used.

**Comment by SS-TruMinds** [comment]
We have been able to reproduce the crash with debug symbols enabled. Please find the backtrace below. 
This is with Release 0.8.1:

`0  libhiredis_cluster.so.0.8!redisClusterAsyncRetryCallback [hircluster.c : 3907 + 0x0]`
`1  libhiredis.so.1.0.0!__redisAsyncFree [async.c : 287 + 0x9]`
`2  libhiredis.so.1.0.0!redisProcessCallbacks [async.c : 577 + 0x8]`
`3  redisLibmyeventHandler(int, unsigned int, base::SystemInfo) [hiredis_libmyevent.h : 89 + 0x5]`

**Comment by SS-TruMinds** [comment]
Some input from one of the team members below. Please see if this seems plausible:

"It seems this is simply that

- when `cluster_node_deinit` calls `redisAsyncFree`, it first sets `ac->data` to `NULL`
- `__redisAsyncFree` calls all of the pending callbacks
- `redisClusterAsyncRetryCallback` assumes that `ac->data` is non-`NULL`
- so if one of those callbacks is `redisClusterAsyncRetryCallback`, we hit this crash.

So why don't we hit this crash all the time?

I suspect that normally, `cluster_node_deinit` is called from the `redisClusterAsyncRetryCallback`, invoked on its own context. As a result, the `redisClusterAsyncRetryCallback` has already been invoked by the time `redisAsyncFree` is hit, and so isn't pending.

In this case, `clusterNode_deinit` is called from the `redisClusterAsyncRetryCallback` invoked on a different context, i.e. an event occured on the connection to Redis node 1 that caused us to decide that Redis node 2 should be de-initialized. We know this is true because `redisAsyncFree` would not call `__redisAsyncFree` synchronously if it was invoked on the same context.

I suspect the fix is simply for `redisClusterAsyncCallback` to check if `ac->data` is non-`NULL` (and adding an extensive comment to explain how this could happen). The alternative could be to unregister these callbacks in `cluster_node_deinit` before calling `redisAsyncFree`."

**Comment by bjosv** [comment]
Great investigation. I managed to reproduce the problem via a testcase, without any extra threads.
Prepared the PR #112
