### ISSUE TITLE
Re-connect issues after Redis node restart

### ISSUE THREAD

**Issue by SS-TruMinds** [Nordix/hiredis-cluster#119]
Hi,

We have a test where multiple clients are connected to the cluster and continuously performing CRUD operations on a set of keys.

When we restart a Redis node, we notice that some clients re-connect to the node within seconds after the node has come back up.

Some other clients on the other hand take up to 5 minutes to re-connect. 
On these nodes, we see that we keep receiving connect callbacks with `status` being `REDIS_ERR`, and `errstr` of `redisAsyncContext` says "Connection timed out".
The connection eventually gets re-established.

Kindly help debug the issue.

Thank you.

**Comment by bjosv** [comment]
What is the used connection timeout configuration in hiredis-cluster?
It is controlled by `redisClusterSetOptionConnectTimeout()`
Without any configuration it might result in long timeouts depending on setup.

**Comment by bjosv** [comment]
Sounds good with the configured timeout.

If I understand correctly you are running in Kubernetes, and I guess you have tried to manually setup a connection from the hiredis-cluster pod to the Redis pod? Like using telnet just to make sure the connection should work.
Another option would be to increase the logging in the redis node which would tell if redis sees the connection attempt.

Another area that might affect is the eventsystem that is needed for async.
Are you using an own implementation, or a public one that we have tested or can use to try to reproduce the problem?
When hiredis attempts to connect to a node it registers the socket to the eventsystem, which poll the socket for a write event or to have it timeout as in your case. This might affect the results as well.

**Comment by SS-TruMinds** [comment]
Our adapter is based on the reference adapter. It is similar to the ones in your repo and is well tested.

Ok, we will check if there could be any issue with the connectivity to this Redis node. Ideally there shouldn't be, as the other clients running in the same pod are able to re-connect immediately.

**Comment by bjosv** [comment]
This is very likely fixed by #122, please reopen if not.
