### ISSUE TITLE
Async support for cluster nodes call 

### ISSUE THREAD

**Issue by rahulKrishnaM** [Nordix/hiredis-cluster#123]
Hi,

cluster_update_route_by_addr() function today invokes a 'cluster nodes' command and waits synchronously till the response is available.  Since its a blocking call, and hiredis context is single threaded, all other operations go for a halt till the response is received. This impacts the performance of the system, since all other calls application uses are async implemented, and any code flow that reaches here has to wait till the call gets over.

This ticket is a request for an async implementation for supporting the cluster nodes/slots command.

Thanks.

**Comment by zuiderkwast** [comment]
Hi! We now use an asynchronous command for cluster nodes/slots when we see a MOVED-redirect, added in #164, but the initial connect is still blocking. It is being worked on in #171. Feel free to join the discussion if you have any suggestions.
