### ISSUE TITLE
Missing commands: BRPOP, BLPOP, BLMOVE, BLMPOP, BRPOPLPUSH 

### ISSUE THREAD

**Issue by youfeiyou** [Nordix/hiredis-cluster#129]

**Comment by zuiderkwast** [comment]
Hello. Can you give more information. Exactly how do you call the function?

**Comment by youfeiyou** [comment]
> 

`auto cc=redisClusterContextInit();
redisClusterSetOptionPassword(cc,"11111111")
redisClusterSetOptionAddNodes(cc,"192.168.1.129:8000,192.168.1.175:8001")
redisClusterConnect2(cc)
if(cc==nullptr||cc->err!=0){
srd::cerr << ""<<std::endl;
}
redisReply* re=(redisReply*)redisClusterCommand(cc,"BRPOP lists key 10");
std::cout << cc->errstr << std::endl;
`

output: 
Parse command error. Cmd type: 0 ,State: 5, break position: 13.

**Comment by youfeiyou** [comment]
`auto cc=redisClusterContextInit(); redisClusterSetOptionPassword(cc,"11111111") redisClusterSetOptionAddNodes(cc,"192.168.1.129:8000,192.168.1.175:8001") redisClusterConnect2(cc) if(cc==nullptr||cc->err!=0){ srd::cerr << ""<<std::endl; } redisReply* re=(redisReply*)redisClusterCommand(cc,"BRPOP lists key 10"); std::cout << cc->errstr << std::endl; `

**Comment by zuiderkwast** [comment]
Thanks! Your code looks right. I see now that hiredis-cluster doesn't know BRPOP. It is missing in command.c where all the commands are listed. It seems like all blocking list commands are missing: BLPOP, BLMOVE, BLMPOP, BRPOPLPUSH.

We can add them. If you find more missing commands, we can add them too.
