### ISSUE TITLE
Get from Slaves

### ISSUE THREAD

**Issue by SS-TruMinds** [Nordix/hiredis-cluster#131]
Hello,

Is it possible to connect to Slaves in order to perform some GET operations?
If yes, how can this be achieved? Also, will we get the connect/disconnect callbacks from the Slaves too?
Kindly advise.

Thank you.

**Comment by zuiderkwast** [comment]
Hi! It's not implemented yet. We have thought about it though.

If we add it, I think it should be with an option so the default will still be to use only masters. If replicas are used, I suppose the callbacks should be called for replicas too, but I haven't though about it much. What do you think?

Are you interested in contributing an implementation?

**Comment by SS-TruMinds** [comment]
Thank you for the response.

Though not possible at the moment, we will certainly look to contribute whenever we can.
