### ISSUE TITLE
Setting redis password  for  redisClusterAsyncContext 

### ISSUE THREAD

**Issue by dembekadam** [Nordix/hiredis-cluster#141]
I see redisClusterSetOptionPassword(redisClusterContext *cc, ) in hircluster.h but how this can be used with redisClusterAsyncContext ?

In async example the context is created together with connect

redisClusterAsyncContext *cc =
    redisClusterAsyncConnect(nodes.c_str(), HIRCLUSTER_FLAG_NULL);
if (cc && cc->err) {
    printf("Error: %s\n", cc->errstr);
    return 1;
}

Is it possible to pass redisClusterContext with password to redisClusterAsyncContext before connect ?

**Comment by bjosv** [comment]
Hi,
you should be able to do that like we do in the tests.
See for details:
https://github.com/Nordix/hiredis-cluster/blob/master/tests/ct_connection.c#L321

**Comment by dembekadam** [comment]
Thanks, it works fine.
