### ISSUE TITLE
When is the support for redis 7 coming? Any recommendation for which redis client to use for redis version 7?

### ISSUE THREAD

**Issue by abhinavbansal19961996** [Nordix/hiredis-cluster#155]
When is the support for redis 7 coming? Any recommendation for which redis client to use for redis version 7?

**Comment by zuiderkwast** [comment]
Which features or commands from redis 7 do you need?

**Comment by abhinavbansal19961996** [comment]
We are currently using Hiredis-vip  and we want all of those commands which we are using in redis 6 to work in redis 7. I read that redis 7 is not backward compatible. So I dont need any extra features of redis 7. I want my redis client https://github.com/vipshop/hiredis-vip to work for both 7 and 6.

**Comment by abhinavbansal19961996** [comment]
Just to give you list we are using currently:
redisClusterContextInit
redisClusterSetOptionAddNodes
redisClusterSetOptionRouteUseSlots
redisClusterSetOptionConnectTimeout
redisClusterSetOptionTimeout
redisClusterGetReply
redisClusterConnect2
redisClusterAppendCommand (LUA Script)

**Comment by zuiderkwast** [comment]
> I read that redis 7 is not backward compatible.

Where did you read this? In the Release nodes (https://github.com/redis/redis/blob/7.0/00-RELEASENOTES) there are only some very obscure cases that are listed as breaking changes. Are you affected by any of those?

I don't think any of those breaking changes for Redis 7 affect the implementation of clients, so there are no changes needed in the clients as far as I can tell, but please let me know if I'm wrong.

**Comment by bjosv** [comment]
We run the tests towards a range of Redis versions in CI, like [7.0.0](https://github.com/Nordix/hiredis-cluster/actions/runs/4809586853/jobs/8561047799#step:10:8).
If there is anything you have found missing we should fix that.

**Comment by zuiderkwast** [comment]
To be clear, hiredis-cluster is fully backwards compatible with hiredis-vip. We only added bug fixes and more features. I think hiredis-cluster is better for all Redis versions, for Redis Cluster. If you use Redis Standalone, use the simple hiredis client.

**Comment by abhinavbansal19961996** [comment]
We have a cluster of redis. When calling below function:
  redisClusterConnect2(r->ctxt);

Command(cluster slots) reply error: nodes sub_reply is not an correct array.

**Comment by abhinavbansal19961996** [comment]
I tested by running on redis cluster 7 and 6 locally. For 7 it was throwing above error. Any idea, when will fix be applied? We have a deadline or we might have to move to different client or understand this code better and apply patch on our end

**Comment by zuiderkwast** [comment]
We can apply a fix as soon as we have a fix. First we must understand the problem. This message is very helpful:

> Command(cluster slots) reply error: nodes sub_reply is not an correct array.

It is coming from `parse_cluster_slots` in hircluster.c, which is the function that handles the reply of the CLUSTER SLOTS command. Hiredis-cluster sends this command to Redis and Redis replies with a structure that has an unexpected format. I can't understand exactly why it is happening. There is no change in Redis 7 that can explain this.

Can you connect to Redis using `redis-cli` and send `CLUSTER SLOTS` and post the output here?

Then we can understand exactly what Redis is sending. Maybe there is some configuration that affects the result. Because normally we don't get this problem with Redis 7. We have automatic tests with Redis 7.0.0, see here: https://github.com/Nordix/hiredis-cluster/actions/runs/5320977474/jobs/9635455795

**Comment by abhinavbansal19961996** [comment]
I think i got the issue. Since we are using hirendis-vip, there is a bug in hirendis-vip, I checked the code.
https://redis.io/commands/cluster-slots/
New fields have been added and  the below condition will never be true for redis 7 since in redis 7 total length is 4 instead of 3:
https://github.com/vipshop/hiredis-vip/blob/master/hircluster.c#LL856C22-L856C46

Let me try upgrading our library to hiredis-cluster since i see in hirendis-cluster, these checks are updated.

**Comment by zuiderkwast** [comment]
That's great! It makes sense.

I tried to find in which commit we changed this. Now I found it. It was fixed here: 0e741c6dd80063b76ee0e19792d489d3056fb0f9. The fix is included in 0.8.0 and later.

I'm closing the issue again, but feel free to open it again if it still doesn't work.
