### ISSUE TITLE
Support custom commands defined in Redis modules

### ISSUE THREAD

**Issue by selcukaltinay** [Nordix/hiredis-cluster#162]
I'm trying to use redis modules with hiredis-cluster. In previous version of hiredis-cluster, it is possible to add commands to command.h in order to use the redis commands like FT.CREATE which comes from redisearch. But in the last version, there is a script which is named as gencommands.py to produce cmddef.h. As far as I know, I need to add commands to this file to produce QUERY to send redis server. But I couldn't have make it for RediSearch and RedisJSON. I'm giving the json which is located in redisjson and redisearch as an argument my I'm taking an error. How can I use redisearch and redisjson with hiredis-cluster?

**Comment by zuiderkwast** [comment]
It's a good question. We didn't think about custom module commands when we rewrote command.h, but of course we need to support this.

I think we need to provide a way to extend the command definition, either at compile time or in runtime. We have to think about the best way to do this.

In the meantime, there is one workaround: You can use `redisClusterGetNodeByKey` and then `redisClusterCommandToNode` (or the similar functions for async API) to send any command to the specified node.

**Comment by selcukaltinay** [comment]
Thanks for answer. I tried to make your suggestions like this

std::string key = "{my_key}";
cluster_node * node = redisClusterGetNodeByKey(cc, key);
*reply = (redisReply *) redisClusterCommandToNode(cc, node, strCommand.c_str());


But I'm taking "Resource Temporarily Unavailable" error when I try to run the program

Thanks again

**Comment by zuiderkwast** [comment]
I'm not very good with C++ but I guess `key` needs to be a `char *` instead of a `std:string`. Can this be the problem?

Or maybe "Resource Temporarily Unavailable" means there is a temporary network problem, your Redis cluster is not available?

**Comment by bjosv** [comment]
Maybe its a copy&paste error but you should need to give `key.c_str()` to `redisClusterGetNodeByKey()` too,
then if you are using the async api (?) you should use `redisClusterAsyncCommandToNode()`.

**Comment by selcukaltinay** [comment]
The resource unavailable problem fixed with using placeholders as %s, command instead of giving full string with c_str method.
And also suggested work around worked fine. Thanks for answers
