### ISSUE TITLE
There is no way to perform AUTH in asynchronous mode.

### ISSUE THREAD

**Issue by arwace** [Nordix/hiredis-cluster#165]
There is no way to perform AUTH in asynchronous mode.
Please let me know what is possible

**Comment by bjosv** [comment]
It should be possible, there is an example in the tests that might be helpful:
https://github.com/Nordix/hiredis-cluster/blob/16f8abccb3700b862123b0c046b479b93ea6e541/tests/ct_connection.c#L345C1-L372

**Comment by arwace** [comment]
> It should be possible, there is an example in the tests that might be helpful: https://github.com/Nordix/hiredis-cluster/blob/16f8abccb3700b862123b0c046b479b93ea6e541/tests/ct_connection.c#L345C1-L372

Thank you.
This is work fine.
