### ISSUE TITLE
Compilation error LIBEVENT_INCLUDES-NOTFOUND

### ISSUE THREAD

**Issue by selcukaltinay** [Nordix/hiredis-cluster#170]
Hey everyone,

I'm taking an error when I try to compile hiredis-cluster with latest version of both hiredis and hircluster.

The compilation steps listed below;

mkdir build
cmake .. -Dhiredis_DIR:PATH=$HIREDISPATH

Then the error occurs like listed below;

CMake Error in tests/CMakeLists.txt:
   Found relative path while evaluating include directories of "clusterclient_reconnect_async":
     "LIBEVENT_INCLUDES-NOTFOUND"
I'm trying to use libevent library from /usr/lib64 and its already added to LD_LIBRARY_PATH.

I'm trying to fix another error. When I use the async apis for subscription, I'm taking crash. During publishing a message, the subscriber process giving a message like that redisProcessCallbacks: Assertion `(c->flags & 0x20 || c->flags & 0x40)' failed.

I assumed that the problem can be caused for this compilation error. 
Thanks for answers :)

**Comment by bjosv** [comment]
Lets see if I can cover all your issues.

To avoid the `LIBEVENT_INCLUDES-NOTFOUND` error you can use `-DDISABLE_TESTS=ON` as an argument to cmake, see [build instructions](https://github.com/Nordix/hiredis-cluster#build-instructions). This will skip tests which require libevent.

If I understand correctly you have a specific hiredis downloaded which you want to use.
Would this [example](https://github.com/Nordix/hiredis-cluster/blob/master/examples/using_cmake_separate/build.sh
) help? Its an example of building hiredis and hiredis-cluster separate using CMake.

The assert seems to indicate that your build uses an old, possibly system-installed, hiredis.

**Comment by zuiderkwast** [comment]
Additionally, pubsub doesn't work in hiredis-cluster...

**Comment by bjosv** [comment]
Closing since the build instructions covers the issues.
The missing pubsub support in covered by #27.
