### ISSUE TITLE
Target "hiredis::hiredis" because target  "hiredis" is not a library

### ISSUE THREAD

**Issue by abhinavbansal19961996** [Nordix/hiredis-cluster#173]
Getting below error:
```
Detected version: 0.10.0
Expecting to find dependencies in path..
CMake package for 'hiredis' not found, searching for the library..
CMake Error at CMakeLists.txt:137 (add_library):
  add_library cannot create ALIAS target "hiredis::hiredis" because target
  "hiredis" is not a library.

```
Note that i am cloning hiredis library seperately. When i removed above lines  and replaced hiredis::hiredis with hiredis. It succeeded.

**Comment by bjosv** [comment]
After some investigations I can see your error when using an older CMake version (<3.15).
The issue can only be seen when one build+install hiredis using Make directly and then build hiredis-cluster using CMake.

[CMake 3.15](https://cmake.org/cmake/help/v3.15/release/3.15.html#commands) added the functionality that we use for this case:
```
The add_library() command ALIAS option learned to support import libraries of the UNKNOWN type.
```
I'll see if we can handle it differently in our CMakeLists (or add some new build error printouts about how to proceed).
