### ISSUE TITLE
During cmake, Checking for module 'glib-2.0'   No package 'glib-2.0' found

### ISSUE THREAD

**Issue by abhinavbansal19961996** [Nordix/hiredis-cluster#174]
During cmake, getting below error:
```
Checking for module 'glib-2.0'   No package 'glib-2.0' found
```

**Comment by zuiderkwast** [comment]
It is not an error. Building for glib is optional. Cmake checks if glib is installed. Are you using glib?

**Comment by bjosv** [comment]
This is no error as mentioned before.
CMake prints this kind of information from its `pkg-config` module when searching for libraries.
