### ISSUE TITLE
Failed to find keys of command XREADGROUP

### ISSUE THREAD

**Issue by zyhuf** [Nordix/hiredis-cluster#186]
The following command is throwing an error. Why isn't this format supported?
XREADGROUP GROUP XX XX COUNT 1 STREAMS XX >

**Comment by zuiderkwast** [comment]
Thanks for the report.

We use a Python script to extract the syntax of each command given in Redis JSON files. Then we turn this into a C array and we have some C code to find the keys in a command based on this.

In XREADGROUP, the keys are not in a fixed position, but it's located after the 'STREAMS' keyword, which can be in any position of the command. That's probably why we don't handle this yet, but I don't remember exactly.

**Comment by zuiderkwast** [comment]
There is special code for XREAD and XREADGROUP but it was untested and obviously it wasn't working.

I'm fixing it and adding a test case in #187.
