### ISSUE TITLE
async api

### ISSUE THREAD

**Issue by dandyhuang** [Nordix/hiredis-cluster#19]
Will it block when the cluster node connection fails?

**Comment by bjosv** [comment]
The current behavior has currently not changed compared to hiredis-vip.
When a connection to a cluster node gets disconnected the registered event system will receive a disconnect event.
Then after the user has done configured max_redirect _count attempts to reach this node (+ a timer..) there will be an update of the slots/nodes routing table using any node.
This update will trigger an attempt to connect to the chosen node, but as it is now, this is not done in a non-block fashion..
If a timeout has been configured this will avoid a longer block, but still, it is not using the non-block connect API in hiredis..
This needs to be fixed.
Another improvement would be to use an already connected node for updating the slots/route info.

Please comment if this was the right scenario. Sorry for the late response.

**Comment by bjosv** [comment]
This behavior was corrected in #144.
