### ISSUE TITLE
SIGSEGV in clusterNodesReplyCallback while calling redisClusterAsyncFree

### ISSUE THREAD

**Issue by 9chu** [Nordix/hiredis-cluster#194]
![image](https://github.com/Nordix/hiredis-cluster/assets/4137042/ee262ca2-5797-4f33-aafe-7f8d6dfe3f95)

it seems there should be a free barrier in `clusterNodesReplyCallback `.

a patch can by applied to solve this issue:

```patch
diff --git a/hircluster.c b/hircluster.c
index 7ea0c82..d934537 100644
--- a/hircluster.c
+++ b/hircluster.c
@@ -1494,6 +1494,8 @@ void redisClusterFree(redisClusterContext *cc) {
     if (cc == NULL)
         return;

+    cc->flags |= REDIS_FREEING;
+
     if (cc->event_callback) {
         cc->event_callback(cc, HIRCLUSTER_EVENT_FREE_CONTEXT,
                            cc->event_privdata);
@@ -3866,6 +3868,9 @@ static redisClusterNode *selectNode(dict *nodes) {
  * arbitrary connected node is selected. */
 static int updateSlotMapAsync(redisClusterAsyncContext *acc,
                               redisAsyncContext *ac) {
+    if (acc->cc->flags & REDIS_FREEING) {
+        return REDIS_ERR;
+    }
     if (acc->lastSlotmapUpdateAttempt == SLOTMAP_UPDATE_ONGOING) {
         /* Don't allow concurrent slot map updates. */
         return REDIS_ERR;
```

**Comment by zuiderkwast** [comment]
Thanks for your report and analysis! We will look at this within the next days.

**Comment by zuiderkwast** [comment]
`REDIS_FREEING` is a flag for redisContext (hiredis), not the cluster context, so it is a bit confusing to use this flag here. I think #195 is a better way to solve it.

**Comment by 9chu** [comment]
> `REDIS_FREEING` is a flag for redisContext (hiredis), not the cluster context, so it is a bit confusing to use this flag here. I think #195 is a better way to solve it.

You're right, my patch here is just a temporary fix.
I'll take a look at the PR, thank you.
