### ISSUE TITLE
Cannot pass command with va_list to specific node

### ISSUE THREAD

**Issue by unikmhz** [Nordix/hiredis-cluster#230]
If I understand correctly, current API does not provide redisClustervCommandToNode() or something similar.

Therefore passing variadic commands to specific node is currently done using dirty hacks in code and duplication of parts of library code.

Is there any possibility of adding this API to hiredis-cluster? Thanks.

**Comment by bjosv** [comment]
Sure! A PR is welcomed.

**Comment by unikmhz** [comment]
Ok, will cook something up on the weekend. Thanks.
