### ISSUE TITLE
Support AUTH with username

### ISSUE THREAD

**Issue by bjosv** [Nordix/hiredis-cluster#42]
**Background**
Redis 6 introduced Access Control List that can allow certain connections to be limited in terms of the commands that can be executed and the keys that can be accessed.

The Redis AUTH command was also extended in Redis 6, to enable authentication as a specific user:

`AUTH <username> <password>`

**Requested functionality**
Currently the API only supports the legacy authentication method using password via:
```
int redisClusterSetOptionPassword(redisClusterContext *cc,
                                  const char *password);
```
API support for specifying a `username` is needed.

**Misc**
Redis 6 will internally use the username `default` if no username is given in `AUTH`

**Links**
https://redis.io/topics/acl
https://redis.io/commands/auth

**Comment by zuiderkwast** [comment]
So, we let the username be NULL internally until set by the user and we send `AUTH username password` if username is set and `AUTH password` if username is NULL, right? This makes it compatible with Redis < 6.

**Comment by darkrift** [comment]
That would be a good way to keep backward compat while still support ACL for redis >= 6

> So, we let the username be NULL internally until set by the user and we send `AUTH username password` if username is set and `AUTH password` if username is NULL, right? This makes it compatible with Redis < 6.
