### ISSUE TITLE
Add a static analyzer to CI

### ISSUE THREAD

**Issue by bjosv** [Nordix/hiredis-cluster#46]
By running a static analyzer tool during CI we could find dead code, faulty initiations and more.
Options might be Coverity or Clang static analyzer, or other.

**Comment by andreasgerstmayr** [comment]
I'm quite surprised how well static analysis with Coverity works (#44 and #45 were both found by Coverity), so I registered the project at Coverity Scan. I already prepared the GitHub Actions workflow and submitted a first build, now we just need to wait until the Coverity admins approve this project (afaics there is a manual review).

**Comment by bjosv** [comment]
Nice! I have only run the commercial variant of Coverity, but this tool should be one of the better ones. Really great that its free for open source!
