### ISSUE TITLE
What can I do to modify the code in purpose of  making  it adapt to libev

### ISSUE THREAD

**Issue by mingyuegx** [Nordix/hiredis-cluster#48]
My project contains libev instead of libevent, so what can I do to modify the code in purpose of  making  it adapt to libev？

**Comment by bjosv** [comment]
You need to create a new adapter for libev, and you should probably be able to reuse:
https://github.com/vipshop/hiredis-vip/blob/master/adapters/libev.h

If you get the new adapter running with hiredis-cluster you are always welcome to push a PR.

**Comment by bjosv** [comment]
The adapter for libev and an usage example/test is now added to the repo.
Hope it helps.
