### ISSUE TITLE
The file dict.h is not installed

### ISSUE THREAD

**Issue by dluongiop** [Nordix/hiredis-cluster#51]
It seems that cmake is not installing the file dict.h because it's missing from CMakeLists.h?

```
install(FILES hircluster.h adlist.h hiarray.h dict.h
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/hiredis_cluster)
```

**Comment by zuiderkwast** [comment]
Good catch. Please submit a PR.

**Comment by dluongiop** [comment]
I tried to create a branch for the PR but I don't have permission?

```
ERROR: Permission to Nordix/hiredis-cluster.git denied to dluongiop.
fatal: Could not read from remote repository.
 
Please make sure you have the correct access rights
```

**Comment by zuiderkwast** [comment]
You can't push to nordix. You have to fork it, which means cloning it under you own user name.

**Comment by dluongiop** [comment]
Thank you. I'm new to this process so please bear with me.

I forked and created a PR for the patch. I'm not sure if I need to do anything else to make the PR visible to you.

**Comment by zuiderkwast** [comment]
I can't see it. You need to push your changes to your fork and then click to create a pull request to make it visible. Then it will be visible under [*Pull requests*](https://github.com/Nordix/hiredis-cluster/pulls) for this repo.

Here is some documentation from GitHub: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by dluongiop** [comment]
I think the PR is now visible in Nordix/hiredis-cluster.

**Comment by bjosv** [comment]
#52 is merged now, thank you!
