### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by alankwon** [Nordix/hiredis-cluster#56]
Just a minor issue I noticed while building the project. It's supposed to be version 0.6.0, but it's building as version 0.5.0. It looks like CMakeLists.txt is getting the version from the preprocessor directives in hicluster.h. They should be updated to:

#define HIREDIS_CLUSTER_MAJOR 0
**#define HIREDIS_CLUSTER_MINOR 6**
#define HIREDIS_CLUSTER_PATCH 0
**#define HIREDIS_CLUSTER_SONAME 0.6**

**Comment by zuiderkwast** [comment]
We should fix this when we tag the next version.
