### ISSUE TITLE
What can i do with multiple threads?

### ISSUE THREAD

**Issue by mingyuegx** [Nordix/hiredis-cluster#57]
Excuse me, my application scenario is that multiple threads will call the redis api to write message. What can I do with the connection handle "redisClusterContext *cc"? Create one per thread

**Comment by bjosv** [comment]
hiredis-cluster uses hiredis under the hood which itself does not provide any thread safety (See note in https://github.com/redis/hiredis#connecting).
The straightforward approach currently would be to have one context per thread.
