### ISSUE TITLE
does hiredis-cluster support eval of lua script

### ISSUE THREAD

**Issue by starboy520** [Nordix/hiredis-cluster#58]

**Comment by bjosv** [comment]
Yes, eval is supported.

There are examples of this in our tests, see:
https://github.com/Nordix/hiredis-cluster/blob/master/tests/ct_commands.c#L143

**Comment by zuiderkwast** [comment]
We have a plan to add a list of all supported commands in a markdown file.

**Comment by starboy520** [comment]
It'seems redisClusterContext. are not thread safe? 
beacase when the redisReply are nullptr, need get cc->err;

**Comment by zuiderkwast** [comment]
> It'seems redisClusterContext. are not thread safe?

That's correct. Even hiredis (without cluster) is not thread safe. See #57.

**Comment by starboy520** [comment]
> > It'seems redisClusterContext. are not thread safe?
> 
> That's correct. Even hiredis (without cluster) is not thread safe. See #57.

thanks for reply,
another question :
   when the cluster are adding or removing node with the migrate command 
   can hiredis_cluster process this?

**Comment by starboy520** [comment]
> > It'seems redisClusterContext. are not thread safe?
> 
> That's correct. Even hiredis (without cluster) is not thread safe. See #57.

thanks for reply,
another question :
   when the cluster are adding or removing node with the migrate command 
   can hiredis_cluster process this?

**Comment by zuiderkwast** [comment]
Yes, if the cluster has moved or is in the process of moving slots from one node to another, the node will reply with a MOVED or ASK redirect and hiredis-cluster will follow the redirect and update the slot mapping using CLUSTER SLOTS, as described in https://redis.io/topics/cluster-spec#redirection-and-resharding.
