### ISSUE TITLE
how to use 'KEYS *'

### ISSUE THREAD

**Issue by yongjames** [Nordix/hiredis-cluster#63]
I want to get all keys in redis cluster，and i use "(redisReply *)redisClusterCommand(g_redis_cluster_conn, "KEYS *")",  but , this returns NULL

please help me, much THX

**Comment by bjosv** [comment]
`KEYS` is currently not supported in the `redisClusterCommand()` which sends the command to each instance of the cluster.
The option would be to use `redisClusterCommandToNode()` instead, like this example:
```
nodeIterator ni;
initNodeIterator(&ni, cc);

cluster_node *node;
while ((node = nodeNext(&ni)) != NULL) {
    redisReply *reply;
    reply = redisClusterCommandToNode(cc, node, "KEYS *");
    ....
    freeReplyObject(reply);
}
```

But beware what the Redis docs warns about: 
_Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using SCAN or sets._

**Comment by yongjames** [comment]
thanks !!!

**Comment by youguys** [comment]
> the "nodeIterator ni"  don't need to release ?

**Comment by zuiderkwast** [comment]
> > the "nodeIterator ni"  don't need to release ?

Only if you malloc it. In the example above, it is stack allocated. `initNodeIterator()` doesn't allocate anything.

**Comment by youguys** [comment]
> > > the "nodeIterator ni"  don't need to release ?
> 
> Only if you malloc it. In the example above, it is stack allocated. `initNodeIterator()` doesn't allocate anything.

Got it, thanks a lot.
