### ISSUE TITLE
Does hiredis cluster support select command after updating the slot mapping or connecting to the cluster?

### ISSUE THREAD

**Issue by lzj2015** [Nordix/hiredis-cluster#71]
In some special occasions, we hope that redis can be partitioned.
So, does hiredis cluster support select command after updating the slot mapping or connecting to the cluster?

**Comment by zuiderkwast** [comment]
SELECT does not work in Redis Cluster. There is only db 0. Maybe it works if hiredis cluster is used with a standalone Redis instance (no cluster), but then why use hiredis cluster?
