### ISSUE TITLE
redisClusterSetOptionEnableSSL Out of scope

### ISSUE THREAD

**Issue by DaveLanday** [Nordix/hiredis-cluster#73]
I am trying to build "hiredis-cluster" with USE_SSL=1 to connect to an Elasticache Redis cluster and as a minimal test, I am trying to run [example_tls.c](https://github.com/Nordix/hiredis-cluster/blob/master/examples/src/example_tls.c) with my specific cluster node/host and port number.

I am assuming it is a linking issue on my part, except that none of the other "hiredis-cluster" functions are triggering an out-of-scope. But, the crux of the issue is while compiling I get:

```#27 68.73 g++ -std=c++17  app/src/test_tls_cluster.cpp -I./app/include -I/usr/include -L/usr/lib/libhiredis_cluster.a -L/usr/local/lib/libhiredis.a -L/usr/local/lib/libhiredis_ssl.a -lm -lpthread -o app/bin/test_tls_cluster
#27 68.99 app/src/test_tls_cluster.cpp: In function 'int main(int, char**)':
#27 68.99 app/src/test_tls_cluster.cpp:30:5: error: 'redisClusterSetOptionEnableSSL' was not declared in this scope
#27 68.99      redisClusterSetOptionEnableSSL(cc, ssl);
#27 68.99      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#27 69.00 app/src/test_tls_cluster.cpp:30:5: note: suggested alternative: 'redisClusterSetOptionMaxRetry'
#27 69.00      redisClusterSetOptionEnableSSL(cc, ssl);
#27 69.00      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#27 69.00      redisClusterSetOptionMaxRetry
#27 69.04 make: *** [makefile:39: app/bin/test_tls_cluster] Error 1
------
executor failed running [/bin/sh -c chmod u+x ./ILOG_COS_20.10_LINUX_X86_64.bin && 	./ILOG_COS_20.10_LINUX_X86_64.bin -f install.properties && 	make clean && make USE_SSL=1 && 	rm -rf ./CPLEX && 	rm -f ./ILOG_COS_20.10_LINUX_X86_64.bin && 	rm -f ./install.properties && 	rm -f ./makefile && 	rm -rf ./app/src && 	rm -rf ./hiredis && 	rm -rf /usr/include/hiredis;]: exit code: 2
```

Some details: 
      I am compiling in a docker container. The following is how I am building hiredis_cluster in the container:

```# Install hiredis dependencies:
... Some stuff above that works ...
RUN git clone https://github.com/redis/hiredis.git --depth 1 && \
	cd hiredis && \
	make USE_SSL=1 && make install && \
	mkdir /usr/include/hiredis && \
	cp libhiredis.so /usr/lib/ && \
	cp libhiredis_ssl.so /usr/lib && \
	cp libhiredis.a /usr/lib/ && \
	cp libhiredis_ssl.a /usr/lib && \
	cp hiredis.h /usr/include/hiredis/ && \
	cp hiredis_ssl.h /usr/include/hiredis/ && \
	cp read.h /usr/include/hiredis/ && \
	cp sds.h /usr/include/hiredis/ && \
	cp alloc.h /usr/include/hiredis/ && \
	cp async.h /usr/include/hiredis/ && \
	cp -r adapters /usr/include/hiredis/adapters/ && \
	ldconfig

WORKDIR /app

# Install hiredis-cluster dependencies:
RUN git clone https://github.com/Nordix/hiredis-cluster.git --depth 1 && \
	mkdir /usr/include/hiredis_cluster && \
	cd hiredis-cluster && \
	mkdir install && \
	make USE_SSL=1 CFLAGS="-I/usr/include -D_XOPEN_SOURCE=600" LDFLAGS="-L/usr/local/lib" clean install &&\
	cp -r /usr/local/include/hiredis_cluster/ /usr/include/hiredis_cluster/ && \
	cp /usr/local/lib/libhiredis_cluster.so /usr/lib/ && \
	cp /usr/local/lib/libhiredis_cluster.a /usr/lib/ && \
	ldconfig
... Some stuff below that installs other packages that another program requires ...
```

I then call my specific make file to build `test_tls_cluster.cpp` which is literally just the example_tls.c script from the repo with my specific Elasticache Server and a path pointing to a ca-certificate.crt file. The make file builds the binary from the source files via the g++ compiler as shown above in the error message:
```g++ -std=c++17  app/src/test_tls_cluster.cpp -I./app/include -I/usr/include -L/usr/lib/libhiredis_cluster.a -L/usr/local/lib/libhiredis.a -L/usr/local/lib/libhiredis_ssl.a -lm -lpthread -o app/bin/test_tls_cluster```

Can anyone tell me what I am doing wrong?

**Comment by bjosv** [comment]
It looks like there is a need to add a define and possibly change how the libs are linked.

Unfortunately there is a need to enable SSL functions in the headerfile using the define `SSL_SUPPORT`.
This needs to be looked at in a near future since its either scoped of documented enough, adding the info to the readme is a start I guess.
There also seems to be a mix of library paths used when installing the libs and building test_tls_cluster, i.e.`/usr/lib/` vs `/usr/local/lib/`

The following should work:
`g++ -std=c++17 -DSSL_SUPPORT=1 app/src/test_tls_cluster.cpp -I./app/include -I/usr/include -L/usr/lib/ -lhiredis_cluster -lhiredis -lhiredis_ssl -lm -lpthread -o app/bin/test_tls_cluster`
