### ISSUE TITLE
Try to use "keys" command, got "Parse command error. Cmd type: 0, state: 5, break position: 12

### ISSUE THREAD

**Issue by youguys** [Nordix/hiredis-cluster#77]
I was trying to use redisClusterCommandArgv to get data from redis cluster.
Both "set, get, del" work well, but failed for "keys" like "keys xxxxxxxx:*". 
Is "keys"  command unsupported?

**Comment by zuiderkwast** [comment]
Hi! Hiredis-cluster doesn't know which node to send KEYS. Maybe you expect it should send it to all nodes and then aggregate the result? It's not implemented. It's the same issue as #50 for other commands.

You can use the [use the low-level API to send the command to a specific node](https://github.com/Nordix/hiredis-cluster#sending-commands-to-a-specific-node).
