### ISSUE TITLE
Does anybody know how to support nginx's  "event loop " for async request ?

### ISSUE THREAD

**Issue by youguys** [Nordix/hiredis-cluster#78]
Hey, guys.  
I want to use this in nginx for redis cluster support.  But right now,  nginx's event is not supported in the adpater list.

**Comment by bjosv** [comment]
You are right. Currently there is no out-of-the-box support by this project, but the adapter can be provided by a user.

First there is a need to create an adapter for [hiredis](https://github.com/redis/hiredis) and by a quick google I believe something like [this link](https://github.com/slact/nchan/blob/7994951e86a85592b20ff8003891acbb838f6426/src/store/redis/redis_nginx_adapter.c#L139) might work.
This adapter needs to register functions for the different events.

Second step is to create an adapter for hiredis-cluster which registers the attach function, and this function just calls attach on the hiredis adapter like its done in [existing adapters](https://github.com/Nordix/hiredis-cluster/blob/5c9e294f756ac6001c21146cd808f55f960bbb28/adapters/libevent.h#L37). The hiredis-cluster adapters simply forwards the attach to the hiredis adapter where the eventsystem logic is handled.

**Comment by youguys** [comment]
> You are right. Currently there is no out-of-the-box support by this project, but the adapter can be provided by a user.
> 
> First there is a need to create an adapter for [hiredis](https://github.com/redis/hiredis) and by a quick google I believe something like [this link](https://github.com/slact/nchan/blob/7994951e86a85592b20ff8003891acbb838f6426/src/store/redis/redis_nginx_adapter.c#L139) might work. This adapter needs to register functions for the different events.
> 
> Second step is to create an adapter for hiredis-cluster which registers the attach function, and this function just calls attach on the hiredis adapter like its done in [existing adapters](https://github.com/Nordix/hiredis-cluster/blob/5c9e294f756ac6001c21146cd808f55f960bbb28/adapters/libevent.h#L37). The hiredis-cluster adapters simply forwards the attach to the hiredis adapter where the eventsystem logic is handled.

I had seen this "nchan" too,  right now i don't have extra time to research for this， sync first maybe my choice.

**Comment by youguys** [comment]
> So a PR for hiredis would be the first step. @youguys do you want to work on that?

I was quite interested in this,  once  I get free time, i will work on it.

**Comment by bjosv** [comment]
Closing this question.
I'll happily review a `hiredis` PR and  then a `hiredis-cluster` PR when there is nginx event system support in place in `hiredis`. Just CC me in the PR.
