### ISSUE TITLE
Is "select database"  supported in hiredis-cluster ? 

### ISSUE THREAD

**Issue by youguys** [Nordix/hiredis-cluster#82]
I want to chose database 1 instead of databse 0. It seems i need to call "select" command for every slots

**Comment by zuiderkwast** [comment]
No, it's not possible. This is a limitation in Redis Cluster. This is from the documentation of SELECT:

> When using Redis Cluster, the SELECT command cannot be used, since Redis Cluster only supports database zero.

**Comment by youguys** [comment]
> 



> No, it's not possible. This is a limitation in Redis Cluster. This is from the documentation of SELECT:
> 
> > When using Redis Cluster, the SELECT command cannot be used, since Redis Cluster only supports database zero.

Got it, thanks a lot.
