### ISSUE TITLE
get Error: Command(cluster slots) reply error: nodes sub_reply is not an correct array.

### ISSUE THREAD

**Issue by maris205** [Nordix/hiredis-cluster#94]
when run example_ipv4
seems can't connect redis server
redis-sever vesion 7.0

my code:
  redisClusterContext *cc = redisClusterContextInit();
    redisClusterSetOptionAddNodes(cc, "127.0.0.1:30001");
    redisClusterSetOptionConnectTimeout(cc, timeout);
    redisClusterSetOptionRouteUseSlots(cc);
    redisClusterConnect2(cc);
    if (cc && cc->err) {
        printf("Error: %s\n", cc->errstr);
        // handle error
        exit(-1);
    }

**Comment by bjosv** [comment]
This issue is corrected via #97.
Running `example_ipv4` on a Redis 7.0 cluster works fine after that commit.
