### ISSUE TITLE
Crude support for BITFIELD/BITFIELD_RO

### ISSUE THREAD

**Issue by CharlesRaymond1** [Nordix/hiredis-cluster#95]
There's no current way to support the use case where we want to have support for `-ASK` or `-MOVED` with the [BITFIELD](https://redis.io/commands/bitfield/) command. The sole option is to send the [BITFIELD](https://redis.io/commands/bitfield/) command to a single node having the knowledge where this specific key resides (as explained in  #50 ). This forces the client to have a sub-optimal flow when using the command.

As the [BITFIELD](https://redis.io/commands/bitfield/) command will always apply to a single key (single slot), there is also no need to parse the sub-commands. Also, redis executes all bitfield sub-commands in the same execution (see https://github.com/redis/redis/blob/unstable/src/bitops.c#L1136)

Optionally, we can support the [BITFIELD_RO](https://redis.io/commands/bitfield_ro/) as a bonus because the only difference is that it supports the GET command.

**Comment by CharlesRaymond1** [comment]
Created a suggested PR: https://github.com/Nordix/hiredis-cluster/pull/96

**Comment by zuiderkwast** [comment]
I don't know why we try to validate the commands before we send them to redis. We could simply find the first key and then let redis do the validation. It would be much simpler.
